### ISSUE TITLE
How to register new processes to Sprokit?

### ISSUE THREAD

**Issue by ghost** [Kitware/sprokit#8]
I have found following description to Sprokit here:
https://github.com/Kitware/kwiver/blob/dev/add-track-oracle/sprokit/doc/running-notes.md

`Modules are loaded from a set of directories that are configured into the loader at build time. The default directory is 'lib/sprokit' subdirectory of the install tree. Additionally, at build time, The build directory can be added to the loading path by selecting the cmake variable KWIVER_USE_BUILD_TREE
Set environment variable SPROKIT_MODULE_PATH to list directories of loadable modules`

1)
- So I have to put a new module into the subdirectory 'lib/sprokit' and rebuild Kwiver?

2)
Following processes aren't registered.
- kw_archive_writer_process
- kw_print_number_process

I tried to set the environment variable SPROKIT_MODULE_PATH and to rebuild Kwiver, but it didn't worked.
So the question is:
What is the standard approach to register a process to Sprokit?

**Comment by linus-sherrill** [comment]
Sprokit "discovers" processes by looking through the libraries in its module path, so there is no requirement to rebuild sprokit or kwiver to add a new process. That being said, the easiest way to get started might be to add your process to the `sprokit/src/processes/examples` directory and update the `registration.cxx` file.

Here's a longer explanation of how to add processes.

Processes are usually grouped in a directory and linked into a loadable library (e.g. DLL or SO). This directory/library may contain one or more processes. These processes are registered with sprokit at run time by code in an additional file that is executed when the library is loaded. See `sprokit/src/processes/examples/registration.cxx` for an example. This registration file must contain a function called `regsiter_processes()` with C linkage. See `registration.h` for an example of how to do this. This function must be declared with external linkage so it is visible outside of the library. The example file uses a defined symbol that is created by the build process. It may be easier to just use the compiler specific declaration:
- Windows - `__declspec(dllexport)`
- linux/gcc - `__attribute__((__visibility("default")))`

After the library is built, it is easiest to move it to lib/sprokit so it will be found.

The tool processopedia can be used to display information about processes that sprokit can load. This is a good way to see if your process has been discovered.

**Comment by ghost** [comment]
Thank you very much for the detailed explanation.
It helps me a lot.
